export const colors = {
  COLOR_MAIN: '#357425',
  COLOR_MAIN_BACKGROUND: '#ffffff',
  COLOR_LIGHTGRAY_BACKGROUND: '#FBFBFB',
  COLOR_GRAY_BACKGROUND: '#D9D9D9',
  COLOR_DARKGRAY_BACKGROUND: '#CCCCCC',

  COLOR_GRAY_BORDER: '#DCDCDC',

  COLOR_GRAY_TEXT: '#999999',
  COLOR_WHITE_TEXT: '#ffffff',
  COLOR_RED_TEXT: '#ff0000',

  COLOR_FOOTER: '#ECF5E9',
};
