export const colors = {
  COLOR_MAIN: "#357425",
  COLOR_MAIN_BACKGROUND: "#ffffff",
  COLOR_LIGHTGRAY_BACKGROUND: "#FBFBFB",
  COLOR_GRAY_BACKGROUND: "#D9D9D9",
  COLOR_DARKGRAY_BACKGROUND: "#CCCCCC",
  COLOR_REMOVE_BACKGROUND: "#FFC8C8",
  COLOR_LIGHTGREEN_BACKGROUND: "#ECF5E9",
  COLOR_GRAYTAG_BACKGROUND: "#EDEDED",
  COLOR_RED_BACKGROUND: "#EA3131",

  COLOR_BLUE_BUTTON: "#0062D6",

  COLOR_RECEIVE_MESSAGE: "#ECECEC",
  COLOR_SEND_MESSAGE: "#F9F1AE",

  COLOR_GRAY_TAG: "#EBEBEB",

  COLOR_GRAY_BORDER: "#DCDCDC",
  COLOR_GREEN_BORDER: "#357425",

  COLOR_GRAY_TEXT: "#999999",
  COLOR_WHITE_TEXT: "#ffffff",
  COLOR_RED_TEXT: "#ff0000",
  COLOR_LIGHTGRAY_TEXT: "#c4c4c4",
  COLOR_BLUE_TEXT: "#2B7CF5",
  COLOR_DARKGRAY_TEXT: "#7C7C7C",

  COLOR_FOOTER: "#ECF5E9",

  COLOR_HEART: "#F41010",
};
